project:
  type: website

website:
  title: "數聚點"
  background: primary
  search: true
  favicon: android-chrome-512x512.png
  twitter-card:
    site: "@datainpoint"
  opengraph: true
  margin-header: |
    ![](BlueYellowSimpleEsportLogo.png) 
  body-footer: Made with 💜 and [Quarto](https://www.quarto.org), by DATAINPOINT, Inc.
  navbar:
    logo: BlueYellowSimpleEsportLogo.png
    right:
      - about.qmd
      - blog.qmd
      - icon: github
        href: https://github.com/datainpoint
      - icon: twitter
        href: https://twitter.com/datainpoint
format:
  html:
    theme: cosmo
    css: styles.css
    link-external-icon: true
    link-external-newwindow: true